apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "example-pvc-1"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.source: "http" #defaults to http if missing or invalid
    cdi.kubevirt.io/storage.contentType: "kubevirt" #defaults to kubevirt if missing or invalid.
    cdi.kubevirt.io/storage.import.endpoint: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img" # http or https is supported
    cdi.kubevirt.io/storage.import.secretName: "" # Optional. The name of the secret containing credentials for the end point
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
