kind: Pod
apiVersion: v1
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "dd if=/dev/zero of=/tmp/test.data bs=1M count=1000 2>&1"
    volumeMounts:
      - name: hostpath-pvc
        mountPath: "/mnt"
  nodeSelector:
    kubernetes.io/hostname: cnv-executor-qwang-cnv14-node-a9e382-1.example.com
  restartPolicy: "OnFailure"
  volumes:
    - name: hostpath-pvc
      persistentVolumeClaim:
        claimName: hostpath-pvc
