kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath-pvc
  annotations:
    kubevirt.io/provisionOnNode: cnv-executor-qwang-cnv14-node-a9e382-1.example.com
spec:
  storageClassName: kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
