apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: import-registry-archive-dv
spec:
  source:
    registry:
      url: "docker://kubevirt/fedora-cloud-registry-disk-demo"
  contentType: archive
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
# storageClassName: local
