apiVersion: cdi.kubevirt.io/v1beta1 # perallocation is only available on v1beta1
kind: DataVolume
metadata:
  name: preallocated-dv
spec:
  source:
    http:
      url: "http://cnv-qe-server.rhevdev.lab.eng.rdu2.redhat.com/files/cnv-tests/rhel-images/rhel-82.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: hostpath-provisioner
  preallocation: true
