apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-annotation-registry-kubevirt"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.source: "registry"
    cdi.kubevirt.io/storage.import.contentType: "kubevirt" #defaults to kubevirt if missing or invalid.
    cdi.kubevirt.io/storage.import.endpoint: "docker://docker.io/cirros"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Optional: Set the storage class or omit to accept the default
  # storageClassName: local
