apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    app: containerized-data-importer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: kubevirt-hostpath-provisioner
