apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-pvc
  name: vm-pvc
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-pvc
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: mydisk
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - name: mydisk
        persistentVolumeClaim:
          claimName: import-dv-cirros
